// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq8OWV6sjdhGRcDlq6_5VfbWJr5tmFlQo',
    appId: '1:8971056361:web:0e18139ca4e5efdb7cac78',
    messagingSenderId: '8971056361',
    projectId: 'edu-vista-909d2',
    authDomain: 'edu-vista-909d2.firebaseapp.com',
    storageBucket: 'edu-vista-909d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9cXRKc5P7pWVWDREoL_J6hGiPubuTaFI',
    appId: '1:8971056361:android:c18295ef02a3386d7cac78',
    messagingSenderId: '8971056361',
    projectId: 'edu-vista-909d2',
    storageBucket: 'edu-vista-909d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZnbghw8q8DvAyJQNoB4Wd43hSTJKTWkQ',
    appId: '1:8971056361:ios:592fbd6d1678c4527cac78',
    messagingSenderId: '8971056361',
    projectId: 'edu-vista-909d2',
    storageBucket: 'edu-vista-909d2.appspot.com',
    iosBundleId: 'com.example.eduVistaFinalProject',
  );
}
